spring.application.name=auth-api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Conexão com o banco de dados MySQL

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.open-in-view=false

# O caminho relativo './uploads' criará uma pasta 'uploads' onde a API estiver a ser executada.
file.upload-dir=./uploads/

# PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Autenticação JWT
api.security.token.secret=${JWT_SECRET}

